/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppInquiriesRouteImport } from './routes/_app.inquiries'
import { Route as AppInviteRouteImport } from './routes/_app.invite'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppMfaRouteImport } from './routes/_app.mfa'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppRecoverMfaRouteImport } from './routes/_app.recover-mfa'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as ApiCommercePortalJobsRouteImport } from './routes/api.commerce-portal-jobs'
import { Route as AppUsersUserIdRouteImport } from './routes/_app.users.$userId'
import { Route as AppWebsiteIndexRouteImport } from './routes/_app.website.index'
import { Route as AppWebsitePageIdRouteImport } from './routes/_app.website.$pageId'
import { Route as AppWebsiteMediaRouteImport } from './routes/_app.website.media'
import { Route as AppCustomersCompanyCompanyIdRouteImport } from './routes/_app.customers.company.$companyId'
import { Route as AppCustomersGuestGuestIdRouteImport } from './routes/_app.customers.guest.$guestId'
import { Route as AppCustomersRegisteredCustomerIdRouteImport } from './routes/_app.customers.registered.$customerId'
import { Route as AppWebsiteOtherFooterRouteImport } from './routes/_app.website.other.footer'
import { Route as AppWebsiteOtherNavigationRouteImport } from './routes/_app.website.other.navigation'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppInquiriesRoute = AppInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppMfaRoute = AppMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoverMfaRoute = AppRecoverMfaRouteImport.update({
  id: '/recover-mfa',
  path: '/recover-mfa',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCommercePortalJobsRoute = ApiCommercePortalJobsRouteImport.update({
  id: '/api/commerce-portal-jobs',
  path: '/api/commerce-portal-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppWebsiteIndexRoute = AppWebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsitePageIdRoute = AppWebsitePageIdRouteImport.update({
  id: '/website/$pageId',
  path: '/website/$pageId',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteMediaRoute = AppWebsiteMediaRouteImport.update({
  id: '/website/media',
  path: '/website/media',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCompanyCompanyIdRoute =
  AppCustomersCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => AppCustomersRoute,
  } as any)
const AppCustomersGuestGuestIdRoute =
  AppCustomersGuestGuestIdRouteImport.update({
    id: '/guest/$guestId',
    path: '/guest/$guestId',
    getParentRoute: () => AppCustomersRoute,
  } as any)
const AppCustomersRegisteredCustomerIdRoute =
  AppCustomersRegisteredCustomerIdRouteImport.update({
    id: '/registered/$customerId',
    path: '/registered/$customerId',
    getParentRoute: () => AppCustomersRoute,
  } as any)
const AppWebsiteOtherFooterRoute = AppWebsiteOtherFooterRouteImport.update({
  id: '/website/other/footer',
  path: '/website/other/footer',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteOtherNavigationRoute =
  AppWebsiteOtherNavigationRouteImport.update({
    id: '/website/other/navigation',
    path: '/website/other/navigation',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customers': typeof AppCustomersRouteWithChildren
  '/inquiries': typeof AppInquiriesRoute
  '/invite': typeof AppInviteRoute
  '/login': typeof AppLoginRoute
  '/mfa': typeof AppMfaRoute
  '/products': typeof AppProductsRoute
  '/recover-mfa': typeof AppRecoverMfaRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/commerce-portal-jobs': typeof ApiCommercePortalJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/website/$pageId': typeof AppWebsitePageIdRoute
  '/website/media': typeof AppWebsiteMediaRoute
  '/website/': typeof AppWebsiteIndexRoute
  '/customers/company/$companyId': typeof AppCustomersCompanyCompanyIdRoute
  '/customers/guest/$guestId': typeof AppCustomersGuestGuestIdRoute
  '/customers/registered/$customerId': typeof AppCustomersRegisteredCustomerIdRoute
  '/website/other/footer': typeof AppWebsiteOtherFooterRoute
  '/website/other/navigation': typeof AppWebsiteOtherNavigationRoute
}
export interface FileRoutesByTo {
  '/customers': typeof AppCustomersRouteWithChildren
  '/inquiries': typeof AppInquiriesRoute
  '/invite': typeof AppInviteRoute
  '/login': typeof AppLoginRoute
  '/mfa': typeof AppMfaRoute
  '/products': typeof AppProductsRoute
  '/recover-mfa': typeof AppRecoverMfaRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/commerce-portal-jobs': typeof ApiCommercePortalJobsRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/website/$pageId': typeof AppWebsitePageIdRoute
  '/website/media': typeof AppWebsiteMediaRoute
  '/website': typeof AppWebsiteIndexRoute
  '/customers/company/$companyId': typeof AppCustomersCompanyCompanyIdRoute
  '/customers/guest/$guestId': typeof AppCustomersGuestGuestIdRoute
  '/customers/registered/$customerId': typeof AppCustomersRegisteredCustomerIdRoute
  '/website/other/footer': typeof AppWebsiteOtherFooterRoute
  '/website/other/navigation': typeof AppWebsiteOtherNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/inquiries': typeof AppInquiriesRoute
  '/_app/invite': typeof AppInviteRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/mfa': typeof AppMfaRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/recover-mfa': typeof AppRecoverMfaRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/commerce-portal-jobs': typeof ApiCommercePortalJobsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/website/$pageId': typeof AppWebsitePageIdRoute
  '/_app/website/media': typeof AppWebsiteMediaRoute
  '/_app/website/': typeof AppWebsiteIndexRoute
  '/_app/customers/company/$companyId': typeof AppCustomersCompanyCompanyIdRoute
  '/_app/customers/guest/$guestId': typeof AppCustomersGuestGuestIdRoute
  '/_app/customers/registered/$customerId': typeof AppCustomersRegisteredCustomerIdRoute
  '/_app/website/other/footer': typeof AppWebsiteOtherFooterRoute
  '/_app/website/other/navigation': typeof AppWebsiteOtherNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customers'
    | '/inquiries'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/products'
    | '/recover-mfa'
    | '/settings'
    | '/users'
    | '/admin/$'
    | '/api/commerce-portal-jobs'
    | '/admin/'
    | '/users/$userId'
    | '/website/$pageId'
    | '/website/media'
    | '/website/'
    | '/customers/company/$companyId'
    | '/customers/guest/$guestId'
    | '/customers/registered/$customerId'
    | '/website/other/footer'
    | '/website/other/navigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/customers'
    | '/inquiries'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/products'
    | '/recover-mfa'
    | '/settings'
    | '/users'
    | '/admin/$'
    | '/api/commerce-portal-jobs'
    | '/'
    | '/admin'
    | '/users/$userId'
    | '/website/$pageId'
    | '/website/media'
    | '/website'
    | '/customers/company/$companyId'
    | '/customers/guest/$guestId'
    | '/customers/registered/$customerId'
    | '/website/other/footer'
    | '/website/other/navigation'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/customers'
    | '/_app/inquiries'
    | '/_app/invite'
    | '/_app/login'
    | '/_app/mfa'
    | '/_app/products'
    | '/_app/recover-mfa'
    | '/_app/settings'
    | '/_app/users'
    | '/admin/$'
    | '/api/commerce-portal-jobs'
    | '/_app/'
    | '/admin/'
    | '/_app/users/$userId'
    | '/_app/website/$pageId'
    | '/_app/website/media'
    | '/_app/website/'
    | '/_app/customers/company/$companyId'
    | '/_app/customers/guest/$guestId'
    | '/_app/customers/registered/$customerId'
    | '/_app/website/other/footer'
    | '/_app/website/other/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiCommercePortalJobsRoute: typeof ApiCommercePortalJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inquiries': {
      id: '/_app/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AppInquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite': {
      id: '/_app/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mfa': {
      id: '/_app/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AppMfaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recover-mfa': {
      id: '/_app/recover-mfa'
      path: '/recover-mfa'
      fullPath: '/recover-mfa'
      preLoaderRoute: typeof AppRecoverMfaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/commerce-portal-jobs': {
      id: '/api/commerce-portal-jobs'
      path: '/api/commerce-portal-jobs'
      fullPath: '/api/commerce-portal-jobs'
      preLoaderRoute: typeof ApiCommercePortalJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/website/': {
      id: '/_app/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof AppWebsiteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/$pageId': {
      id: '/_app/website/$pageId'
      path: '/website/$pageId'
      fullPath: '/website/$pageId'
      preLoaderRoute: typeof AppWebsitePageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/media': {
      id: '/_app/website/media'
      path: '/website/media'
      fullPath: '/website/media'
      preLoaderRoute: typeof AppWebsiteMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/company/$companyId': {
      id: '/_app/customers/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/customers/company/$companyId'
      preLoaderRoute: typeof AppCustomersCompanyCompanyIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/customers/guest/$guestId': {
      id: '/_app/customers/guest/$guestId'
      path: '/guest/$guestId'
      fullPath: '/customers/guest/$guestId'
      preLoaderRoute: typeof AppCustomersGuestGuestIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/customers/registered/$customerId': {
      id: '/_app/customers/registered/$customerId'
      path: '/registered/$customerId'
      fullPath: '/customers/registered/$customerId'
      preLoaderRoute: typeof AppCustomersRegisteredCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/website/other/footer': {
      id: '/_app/website/other/footer'
      path: '/website/other/footer'
      fullPath: '/website/other/footer'
      preLoaderRoute: typeof AppWebsiteOtherFooterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/other/navigation': {
      id: '/_app/website/other/navigation'
      path: '/website/other/navigation'
      fullPath: '/website/other/navigation'
      preLoaderRoute: typeof AppWebsiteOtherNavigationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersCompanyCompanyIdRoute: typeof AppCustomersCompanyCompanyIdRoute
  AppCustomersGuestGuestIdRoute: typeof AppCustomersGuestGuestIdRoute
  AppCustomersRegisteredCustomerIdRoute: typeof AppCustomersRegisteredCustomerIdRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCompanyCompanyIdRoute: AppCustomersCompanyCompanyIdRoute,
  AppCustomersGuestGuestIdRoute: AppCustomersGuestGuestIdRoute,
  AppCustomersRegisteredCustomerIdRoute: AppCustomersRegisteredCustomerIdRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppInquiriesRoute: typeof AppInquiriesRoute
  AppInviteRoute: typeof AppInviteRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMfaRoute: typeof AppMfaRoute
  AppProductsRoute: typeof AppProductsRoute
  AppRecoverMfaRoute: typeof AppRecoverMfaRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppWebsitePageIdRoute: typeof AppWebsitePageIdRoute
  AppWebsiteMediaRoute: typeof AppWebsiteMediaRoute
  AppWebsiteIndexRoute: typeof AppWebsiteIndexRoute
  AppWebsiteOtherFooterRoute: typeof AppWebsiteOtherFooterRoute
  AppWebsiteOtherNavigationRoute: typeof AppWebsiteOtherNavigationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppInquiriesRoute: AppInquiriesRoute,
  AppInviteRoute: AppInviteRoute,
  AppLoginRoute: AppLoginRoute,
  AppMfaRoute: AppMfaRoute,
  AppProductsRoute: AppProductsRoute,
  AppRecoverMfaRoute: AppRecoverMfaRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppWebsitePageIdRoute: AppWebsitePageIdRoute,
  AppWebsiteMediaRoute: AppWebsiteMediaRoute,
  AppWebsiteIndexRoute: AppWebsiteIndexRoute,
  AppWebsiteOtherFooterRoute: AppWebsiteOtherFooterRoute,
  AppWebsiteOtherNavigationRoute: AppWebsiteOtherNavigationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiCommercePortalJobsRoute: ApiCommercePortalJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
