/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRecoverMfaRouteImport } from './routes/admin.recover-mfa'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminMfaRouteImport } from './routes/admin.mfa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInviteRouteImport } from './routes/admin.invite'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminWebsiteIndexRouteImport } from './routes/admin.website.index'
import { Route as AdminWebsiteMediaRouteImport } from './routes/admin.website.media'
import { Route as AdminWebsitePageIdRouteImport } from './routes/admin.website.$pageId'
import { Route as AdminWebsiteOtherNavigationRouteImport } from './routes/admin.website.other.navigation'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoverMfaRoute = AdminRecoverMfaRouteImport.update({
  id: '/recover-mfa',
  path: '/recover-mfa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteIndexRoute = AdminWebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteMediaRoute = AdminWebsiteMediaRouteImport.update({
  id: '/website/media',
  path: '/website/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsitePageIdRoute = AdminWebsitePageIdRouteImport.update({
  id: '/website/$pageId',
  path: '/website/$pageId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteOtherNavigationRoute =
  AdminWebsiteOtherNavigationRouteImport.update({
    id: '/website/other/navigation',
    path: '/website/other/navigation',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/recover-mfa': typeof AdminRecoverMfaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/website/$pageId': typeof AdminWebsitePageIdRoute
  '/admin/website/media': typeof AdminWebsiteMediaRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/admin/website/other/navigation': typeof AdminWebsiteOtherNavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/recover-mfa': typeof AdminRecoverMfaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/website/$pageId': typeof AdminWebsitePageIdRoute
  '/admin/website/media': typeof AdminWebsiteMediaRoute
  '/admin/website': typeof AdminWebsiteIndexRoute
  '/admin/website/other/navigation': typeof AdminWebsiteOtherNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/recover-mfa': typeof AdminRecoverMfaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/website/$pageId': typeof AdminWebsitePageIdRoute
  '/admin/website/media': typeof AdminWebsiteMediaRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/admin/website/other/navigation': typeof AdminWebsiteOtherNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/inquiries'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/products'
    | '/admin/recover-mfa'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/website/$pageId'
    | '/admin/website/media'
    | '/admin/website/'
    | '/admin/website/other/navigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/inquiries'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/products'
    | '/admin/recover-mfa'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/website/$pageId'
    | '/admin/website/media'
    | '/admin/website'
    | '/admin/website/other/navigation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/inquiries'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/products'
    | '/admin/recover-mfa'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/website/$pageId'
    | '/admin/website/media'
    | '/admin/website/'
    | '/admin/website/other/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recover-mfa': {
      id: '/admin/recover-mfa'
      path: '/recover-mfa'
      fullPath: '/admin/recover-mfa'
      preLoaderRoute: typeof AdminRecoverMfaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/': {
      id: '/admin/website/'
      path: '/website'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AdminWebsiteIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/media': {
      id: '/admin/website/media'
      path: '/website/media'
      fullPath: '/admin/website/media'
      preLoaderRoute: typeof AdminWebsiteMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/$pageId': {
      id: '/admin/website/$pageId'
      path: '/website/$pageId'
      fullPath: '/admin/website/$pageId'
      preLoaderRoute: typeof AdminWebsitePageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/other/navigation': {
      id: '/admin/website/other/navigation'
      path: '/website/other/navigation'
      fullPath: '/admin/website/other/navigation'
      preLoaderRoute: typeof AdminWebsiteOtherNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMfaRoute: typeof AdminMfaRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRecoverMfaRoute: typeof AdminRecoverMfaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWebsitePageIdRoute: typeof AdminWebsitePageIdRoute
  AdminWebsiteMediaRoute: typeof AdminWebsiteMediaRoute
  AdminWebsiteIndexRoute: typeof AdminWebsiteIndexRoute
  AdminWebsiteOtherNavigationRoute: typeof AdminWebsiteOtherNavigationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMfaRoute: AdminMfaRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRecoverMfaRoute: AdminRecoverMfaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWebsitePageIdRoute: AdminWebsitePageIdRoute,
  AdminWebsiteMediaRoute: AdminWebsiteMediaRoute,
  AdminWebsiteIndexRoute: AdminWebsiteIndexRoute,
  AdminWebsiteOtherNavigationRoute: AdminWebsiteOtherNavigationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
