/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppInquiriesRouteImport } from './routes/_app.inquiries'
import { Route as AppInviteRouteImport } from './routes/_app.invite'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppMfaRouteImport } from './routes/_app.mfa'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppRecoverMfaRouteImport } from './routes/_app.recover-mfa'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AppWebsiteIndexRouteImport } from './routes/_app.website.index'
import { Route as AppWebsitePageIdRouteImport } from './routes/_app.website.$pageId'
import { Route as AppWebsiteMediaRouteImport } from './routes/_app.website.media'
import { Route as AppWebsiteOtherFooterRouteImport } from './routes/_app.website.other.footer'
import { Route as AppWebsiteOtherNavigationRouteImport } from './routes/_app.website.other.navigation'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInquiriesRoute = AppInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppMfaRoute = AppMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoverMfaRoute = AppRecoverMfaRouteImport.update({
  id: '/recover-mfa',
  path: '/recover-mfa',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AppWebsiteIndexRoute = AppWebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsitePageIdRoute = AppWebsitePageIdRouteImport.update({
  id: '/website/$pageId',
  path: '/website/$pageId',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteMediaRoute = AppWebsiteMediaRouteImport.update({
  id: '/website/media',
  path: '/website/media',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteOtherFooterRoute = AppWebsiteOtherFooterRouteImport.update({
  id: '/website/other/footer',
  path: '/website/other/footer',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteOtherNavigationRoute =
  AppWebsiteOtherNavigationRouteImport.update({
    id: '/website/other/navigation',
    path: '/website/other/navigation',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inquiries': typeof AppInquiriesRoute
  '/invite': typeof AppInviteRoute
  '/login': typeof AppLoginRoute
  '/mfa': typeof AppMfaRoute
  '/products': typeof AppProductsRoute
  '/recover-mfa': typeof AppRecoverMfaRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/website/$pageId': typeof AppWebsitePageIdRoute
  '/website/media': typeof AppWebsiteMediaRoute
  '/website/': typeof AppWebsiteIndexRoute
  '/website/other/footer': typeof AppWebsiteOtherFooterRoute
  '/website/other/navigation': typeof AppWebsiteOtherNavigationRoute
}
export interface FileRoutesByTo {
  '/inquiries': typeof AppInquiriesRoute
  '/invite': typeof AppInviteRoute
  '/login': typeof AppLoginRoute
  '/mfa': typeof AppMfaRoute
  '/products': typeof AppProductsRoute
  '/recover-mfa': typeof AppRecoverMfaRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/admin/$': typeof AdminSplatRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/website/$pageId': typeof AppWebsitePageIdRoute
  '/website/media': typeof AppWebsiteMediaRoute
  '/website': typeof AppWebsiteIndexRoute
  '/website/other/footer': typeof AppWebsiteOtherFooterRoute
  '/website/other/navigation': typeof AppWebsiteOtherNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/inquiries': typeof AppInquiriesRoute
  '/_app/invite': typeof AppInviteRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/mfa': typeof AppMfaRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/recover-mfa': typeof AppRecoverMfaRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/admin/$': typeof AdminSplatRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/website/$pageId': typeof AppWebsitePageIdRoute
  '/_app/website/media': typeof AppWebsiteMediaRoute
  '/_app/website/': typeof AppWebsiteIndexRoute
  '/_app/website/other/footer': typeof AppWebsiteOtherFooterRoute
  '/_app/website/other/navigation': typeof AppWebsiteOtherNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/inquiries'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/products'
    | '/recover-mfa'
    | '/settings'
    | '/users'
    | '/admin/$'
    | '/admin/'
    | '/website/$pageId'
    | '/website/media'
    | '/website/'
    | '/website/other/footer'
    | '/website/other/navigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inquiries'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/products'
    | '/recover-mfa'
    | '/settings'
    | '/users'
    | '/admin/$'
    | '/'
    | '/admin'
    | '/website/$pageId'
    | '/website/media'
    | '/website'
    | '/website/other/footer'
    | '/website/other/navigation'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/inquiries'
    | '/_app/invite'
    | '/_app/login'
    | '/_app/mfa'
    | '/_app/products'
    | '/_app/recover-mfa'
    | '/_app/settings'
    | '/_app/users'
    | '/admin/$'
    | '/_app/'
    | '/admin/'
    | '/_app/website/$pageId'
    | '/_app/website/media'
    | '/_app/website/'
    | '/_app/website/other/footer'
    | '/_app/website/other/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inquiries': {
      id: '/_app/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AppInquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite': {
      id: '/_app/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mfa': {
      id: '/_app/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AppMfaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recover-mfa': {
      id: '/_app/recover-mfa'
      path: '/recover-mfa'
      fullPath: '/recover-mfa'
      preLoaderRoute: typeof AppRecoverMfaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/website/': {
      id: '/_app/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof AppWebsiteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/$pageId': {
      id: '/_app/website/$pageId'
      path: '/website/$pageId'
      fullPath: '/website/$pageId'
      preLoaderRoute: typeof AppWebsitePageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/media': {
      id: '/_app/website/media'
      path: '/website/media'
      fullPath: '/website/media'
      preLoaderRoute: typeof AppWebsiteMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/other/footer': {
      id: '/_app/website/other/footer'
      path: '/website/other/footer'
      fullPath: '/website/other/footer'
      preLoaderRoute: typeof AppWebsiteOtherFooterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website/other/navigation': {
      id: '/_app/website/other/navigation'
      path: '/website/other/navigation'
      fullPath: '/website/other/navigation'
      preLoaderRoute: typeof AppWebsiteOtherNavigationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInquiriesRoute: typeof AppInquiriesRoute
  AppInviteRoute: typeof AppInviteRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMfaRoute: typeof AppMfaRoute
  AppProductsRoute: typeof AppProductsRoute
  AppRecoverMfaRoute: typeof AppRecoverMfaRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWebsitePageIdRoute: typeof AppWebsitePageIdRoute
  AppWebsiteMediaRoute: typeof AppWebsiteMediaRoute
  AppWebsiteIndexRoute: typeof AppWebsiteIndexRoute
  AppWebsiteOtherFooterRoute: typeof AppWebsiteOtherFooterRoute
  AppWebsiteOtherNavigationRoute: typeof AppWebsiteOtherNavigationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInquiriesRoute: AppInquiriesRoute,
  AppInviteRoute: AppInviteRoute,
  AppLoginRoute: AppLoginRoute,
  AppMfaRoute: AppMfaRoute,
  AppProductsRoute: AppProductsRoute,
  AppRecoverMfaRoute: AppRecoverMfaRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppWebsitePageIdRoute: AppWebsitePageIdRoute,
  AppWebsiteMediaRoute: AppWebsiteMediaRoute,
  AppWebsiteIndexRoute: AppWebsiteIndexRoute,
  AppWebsiteOtherFooterRoute: AppWebsiteOtherFooterRoute,
  AppWebsiteOtherNavigationRoute: AppWebsiteOtherNavigationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
