/**
 * Leaf block-type union — keep free of content/page imports.
 * Must stay in sync with catalog / renderer registries.
 */
export type BlockType =
  | "hero"
  | "richText"
  | "centered"
  | "textImage"
  | "columns"
  | "benefits"
  | "quote"
  | "gallery"
  | "video"
  | "beforeAfter"
  | "carousel"
  | "steps"
  | "comparisonTable"
  | "featureGrid"
  | "spacer"
  | "teamGrid"
  | "teamProfile"
  | "values"
  | "timeline"
  | "roadmap"
  | "plans"
  | "cta"
  | "newsletter"
  | "contactForm"
  | "announcement"
  | "popup"
  | "portfolio"
  | "jobs"
  | "latestPosts"
  | "partnersMarquee"
  | "statsCounters"
  | "contactInfoCards"
  | "quoteRequestForm"
  | "legalArticles"
  | "offers";
