/**
 * Structured publish-validation error codes.
 * Dutch copy lives in admin (`validation-messages.nl.ts`); schema stays locale-agnostic.
 */

export const PUBLISH_VALIDATION_CODES = {
  BLOCK_UNPUBLISHABLE: "BLOCK_UNPUBLISHABLE",
  BLOCK_DATA_INVALID: "BLOCK_DATA_INVALID",
  HERO_TITLE_REQUIRED: "HERO_TITLE_REQUIRED",
  ROADMAP_MILESTONE_TITLE_REQUIRED: "ROADMAP_MILESTONE_TITLE_REQUIRED",
  PLANS_CTA_INVALID: "PLANS_CTA_INVALID",
  PLANS_UNKNOWN_FEATURE: "PLANS_UNKNOWN_FEATURE",
  JOBS_TITLE_REQUIRED: "JOBS_TITLE_REQUIRED",
  JOBS_LOCATION_REQUIRED: "JOBS_LOCATION_REQUIRED",
  JOBS_DESCRIPTION_REQUIRED: "JOBS_DESCRIPTION_REQUIRED",
  JOBS_APPLICATION_LINK_INVALID: "JOBS_APPLICATION_LINK_INVALID",
  JOBS_HOURS_INVALID: "JOBS_HOURS_INVALID",
  JOBS_RATE_INVALID: "JOBS_RATE_INVALID",
  VIDEO_URL_INVALID: "VIDEO_URL_INVALID",
  VIDEO_TITLE_REQUIRED: "VIDEO_TITLE_REQUIRED",
  VIDEO_POSTER_ALT_REQUIRED: "VIDEO_POSTER_ALT_REQUIRED",
  BEFORE_AFTER_IMAGE_MISSING: "BEFORE_AFTER_IMAGE_MISSING",
  BEFORE_AFTER_ALT_REQUIRED: "BEFORE_AFTER_ALT_REQUIRED",
  GALLERY_EMPTY: "GALLERY_EMPTY",
  GALLERY_IMAGE_ALT_REQUIRED: "GALLERY_IMAGE_ALT_REQUIRED",
  CAROUSEL_EMPTY: "CAROUSEL_EMPTY",
  IMAGE_ALT_REQUIRED: "IMAGE_ALT_REQUIRED",
  NEWSLETTER_TITLE_REQUIRED: "NEWSLETTER_TITLE_REQUIRED",
  NEWSLETTER_BUTTON_REQUIRED: "NEWSLETTER_BUTTON_REQUIRED",
  CONTACT_FORM_TITLE_REQUIRED: "CONTACT_FORM_TITLE_REQUIRED",
  CONTACT_FORM_FIELDS_REQUIRED: "CONTACT_FORM_FIELDS_REQUIRED",
  POPUP_TITLE_REQUIRED: "POPUP_TITLE_REQUIRED",
} as const;

export type PublishValidationCode =
  (typeof PUBLISH_VALIDATION_CODES)[keyof typeof PUBLISH_VALIDATION_CODES];

export type PublishValidationPath = Array<string | number>;

export type PublishValidationError = {
  code: PublishValidationCode | string;
  path: PublishValidationPath;
  /** Optional machine/debug hint — UI should prefer code → NL map. */
  message?: string;
  /** Block type when error is scoped to a layout block. */
  blockType?: string;
  /** Human catalog label when available. */
  blockLabel?: string;
};
