/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacaturesRouteImport } from './routes/vacatures'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchoonmaakbedrijfHengeloRouteImport } from './routes/schoonmaakbedrijf-hengelo'
import { Route as SchoonmaakbedrijfEnschedeRouteImport } from './routes/schoonmaakbedrijf-enschede'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CustomSlugRouteImport } from './routes/$customSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminWebsiteIndexRouteImport } from './routes/admin.website.index'
import { Route as AdminWebsitePageIdRouteImport } from './routes/admin.website.$pageId'

const VacaturesRoute = VacaturesRouteImport.update({
  id: '/vacatures',
  path: '/vacatures',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoonmaakbedrijfHengeloRoute =
  SchoonmaakbedrijfHengeloRouteImport.update({
    id: '/schoonmaakbedrijf-hengelo',
    path: '/schoonmaakbedrijf-hengelo',
    getParentRoute: () => rootRouteImport,
  } as any)
const SchoonmaakbedrijfEnschedeRoute =
  SchoonmaakbedrijfEnschedeRouteImport.update({
    id: '/schoonmaakbedrijf-enschede',
    path: '/schoonmaakbedrijf-enschede',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSlugRoute = CustomSlugRouteImport.update({
  id: '/$customSlug',
  path: '/$customSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteIndexRoute = AdminWebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsitePageIdRoute = AdminWebsitePageIdRouteImport.update({
  id: '/website/$pageId',
  path: '/website/$pageId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$customSlug': typeof CustomSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/offerte': typeof OfferteRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/schoonmaakbedrijf-enschede': typeof SchoonmaakbedrijfEnschedeRoute
  '/schoonmaakbedrijf-hengelo': typeof SchoonmaakbedrijfHengeloRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/vacatures': typeof VacaturesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/website/$pageId': typeof AdminWebsitePageIdRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$customSlug': typeof CustomSlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/offerte': typeof OfferteRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/schoonmaakbedrijf-enschede': typeof SchoonmaakbedrijfEnschedeRoute
  '/schoonmaakbedrijf-hengelo': typeof SchoonmaakbedrijfHengeloRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/vacatures': typeof VacaturesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/website/$pageId': typeof AdminWebsitePageIdRoute
  '/admin/website': typeof AdminWebsiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$customSlug': typeof CustomSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/offerte': typeof OfferteRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/schoonmaakbedrijf-enschede': typeof SchoonmaakbedrijfEnschedeRoute
  '/schoonmaakbedrijf-hengelo': typeof SchoonmaakbedrijfHengeloRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/vacatures': typeof VacaturesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/website/$pageId': typeof AdminWebsitePageIdRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$customSlug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/offerte'
    | '/privacy'
    | '/products'
    | '/schoonmaakbedrijf-enschede'
    | '/schoonmaakbedrijf-hengelo'
    | '/services'
    | '/terms'
    | '/vacatures'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/products'
    | '/admin/users'
    | '/admin/'
    | '/admin/website/$pageId'
    | '/admin/website/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$customSlug'
    | '/about'
    | '/contact'
    | '/offerte'
    | '/privacy'
    | '/products'
    | '/schoonmaakbedrijf-enschede'
    | '/schoonmaakbedrijf-hengelo'
    | '/services'
    | '/terms'
    | '/vacatures'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/products'
    | '/admin/users'
    | '/admin'
    | '/admin/website/$pageId'
    | '/admin/website'
  id:
    | '__root__'
    | '/'
    | '/$customSlug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/offerte'
    | '/privacy'
    | '/products'
    | '/schoonmaakbedrijf-enschede'
    | '/schoonmaakbedrijf-hengelo'
    | '/services'
    | '/terms'
    | '/vacatures'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/products'
    | '/admin/users'
    | '/admin/'
    | '/admin/website/$pageId'
    | '/admin/website/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomSlugRoute: typeof CustomSlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  OfferteRoute: typeof OfferteRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  SchoonmaakbedrijfEnschedeRoute: typeof SchoonmaakbedrijfEnschedeRoute
  SchoonmaakbedrijfHengeloRoute: typeof SchoonmaakbedrijfHengeloRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  VacaturesRoute: typeof VacaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacatures': {
      id: '/vacatures'
      path: '/vacatures'
      fullPath: '/vacatures'
      preLoaderRoute: typeof VacaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schoonmaakbedrijf-hengelo': {
      id: '/schoonmaakbedrijf-hengelo'
      path: '/schoonmaakbedrijf-hengelo'
      fullPath: '/schoonmaakbedrijf-hengelo'
      preLoaderRoute: typeof SchoonmaakbedrijfHengeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schoonmaakbedrijf-enschede': {
      id: '/schoonmaakbedrijf-enschede'
      path: '/schoonmaakbedrijf-enschede'
      fullPath: '/schoonmaakbedrijf-enschede'
      preLoaderRoute: typeof SchoonmaakbedrijfEnschedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$customSlug': {
      id: '/$customSlug'
      path: '/$customSlug'
      fullPath: '/$customSlug'
      preLoaderRoute: typeof CustomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/': {
      id: '/admin/website/'
      path: '/website'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AdminWebsiteIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website/$pageId': {
      id: '/admin/website/$pageId'
      path: '/website/$pageId'
      fullPath: '/admin/website/$pageId'
      preLoaderRoute: typeof AdminWebsitePageIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWebsitePageIdRoute: typeof AdminWebsitePageIdRoute
  AdminWebsiteIndexRoute: typeof AdminWebsiteIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWebsitePageIdRoute: AdminWebsitePageIdRoute,
  AdminWebsiteIndexRoute: AdminWebsiteIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomSlugRoute: CustomSlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  OfferteRoute: OfferteRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  SchoonmaakbedrijfEnschedeRoute: SchoonmaakbedrijfEnschedeRoute,
  SchoonmaakbedrijfHengeloRoute: SchoonmaakbedrijfHengeloRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  VacaturesRoute: VacaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
