/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomSlugRouteImport } from './routes/$customSlug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CmsPreviewRouteImport } from './routes/cms-preview'
import { Route as CmsSyncRouteImport } from './routes/cms-sync'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SchoonmaakbedrijfEnschedeRouteImport } from './routes/schoonmaakbedrijf-enschede'
import { Route as SchoonmaakbedrijfHengeloRouteImport } from './routes/schoonmaakbedrijf-hengelo'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VacaturesRouteImport } from './routes/vacatures'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountActivateRouteImport } from './routes/account.activate'
import { Route as AccountCompanyRouteImport } from './routes/account.company'
import { Route as AccountForgotPasswordRouteImport } from './routes/account.forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountResetPasswordRouteImport } from './routes/account.reset-password'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnSplatRouteImport } from './routes/en.$'
import { Route as VacaturesSlugRouteImport } from './routes/vacatures.$slug'
import { Route as AccountCompanyUsersRouteImport } from './routes/account.company.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSlugRoute = CustomSlugRouteImport.update({
  id: '/$customSlug',
  path: '/$customSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsPreviewRoute = CmsPreviewRouteImport.update({
  id: '/cms-preview',
  path: '/cms-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsSyncRoute = CmsSyncRouteImport.update({
  id: '/cms-sync',
  path: '/cms-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoonmaakbedrijfEnschedeRoute =
  SchoonmaakbedrijfEnschedeRouteImport.update({
    id: '/schoonmaakbedrijf-enschede',
    path: '/schoonmaakbedrijf-enschede',
    getParentRoute: () => rootRouteImport,
  } as any)
const SchoonmaakbedrijfHengeloRoute =
  SchoonmaakbedrijfHengeloRouteImport.update({
    id: '/schoonmaakbedrijf-hengelo',
    path: '/schoonmaakbedrijf-hengelo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesRoute = VacaturesRouteImport.update({
  id: '/vacatures',
  path: '/vacatures',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountActivateRoute = AccountActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCompanyRoute = AccountCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AccountRoute,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/en/$',
  path: '/en/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesSlugRoute = VacaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VacaturesRoute,
} as any)
const AccountCompanyUsersRoute = AccountCompanyUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AccountCompanyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$customSlug': typeof CustomSlugRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cms-preview': typeof CmsPreviewRoute
  '/cms-sync': typeof CmsSyncRoute
  '/contact': typeof ContactRoute
  '/offerte': typeof OfferteRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/schoonmaakbedrijf-enschede': typeof SchoonmaakbedrijfEnschedeRoute
  '/schoonmaakbedrijf-hengelo': typeof SchoonmaakbedrijfHengeloRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vacatures': typeof VacaturesRouteWithChildren
  '/account/activate': typeof AccountActivateRoute
  '/account/company': typeof AccountCompanyRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/en/$': typeof EnSplatRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/en/': typeof EnIndexRoute
  '/account/company/users': typeof AccountCompanyUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$customSlug': typeof CustomSlugRoute
  '/about': typeof AboutRoute
  '/cms-preview': typeof CmsPreviewRoute
  '/cms-sync': typeof CmsSyncRoute
  '/contact': typeof ContactRoute
  '/offerte': typeof OfferteRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/schoonmaakbedrijf-enschede': typeof SchoonmaakbedrijfEnschedeRoute
  '/schoonmaakbedrijf-hengelo': typeof SchoonmaakbedrijfHengeloRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vacatures': typeof VacaturesRouteWithChildren
  '/account/activate': typeof AccountActivateRoute
  '/account/company': typeof AccountCompanyRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/en/$': typeof EnSplatRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/account': typeof AccountIndexRoute
  '/en': typeof EnIndexRoute
  '/account/company/users': typeof AccountCompanyUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$customSlug': typeof CustomSlugRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cms-preview': typeof CmsPreviewRoute
  '/cms-sync': typeof CmsSyncRoute
  '/contact': typeof ContactRoute
  '/offerte': typeof OfferteRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/schoonmaakbedrijf-enschede': typeof SchoonmaakbedrijfEnschedeRoute
  '/schoonmaakbedrijf-hengelo': typeof SchoonmaakbedrijfHengeloRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vacatures': typeof VacaturesRouteWithChildren
  '/account/activate': typeof AccountActivateRoute
  '/account/company': typeof AccountCompanyRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/en/$': typeof EnSplatRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/en/': typeof EnIndexRoute
  '/account/company/users': typeof AccountCompanyUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$customSlug'
    | '/about'
    | '/account'
    | '/cms-preview'
    | '/cms-sync'
    | '/contact'
    | '/offerte'
    | '/privacy'
    | '/products'
    | '/robots.txt'
    | '/schoonmaakbedrijf-enschede'
    | '/schoonmaakbedrijf-hengelo'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vacatures'
    | '/account/activate'
    | '/account/company'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/en/$'
    | '/vacatures/$slug'
    | '/account/'
    | '/en/'
    | '/account/company/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$customSlug'
    | '/about'
    | '/cms-preview'
    | '/cms-sync'
    | '/contact'
    | '/offerte'
    | '/privacy'
    | '/products'
    | '/robots.txt'
    | '/schoonmaakbedrijf-enschede'
    | '/schoonmaakbedrijf-hengelo'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vacatures'
    | '/account/activate'
    | '/account/company'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/en/$'
    | '/vacatures/$slug'
    | '/account'
    | '/en'
    | '/account/company/users'
  id:
    | '__root__'
    | '/'
    | '/$customSlug'
    | '/about'
    | '/account'
    | '/cms-preview'
    | '/cms-sync'
    | '/contact'
    | '/offerte'
    | '/privacy'
    | '/products'
    | '/robots.txt'
    | '/schoonmaakbedrijf-enschede'
    | '/schoonmaakbedrijf-hengelo'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/vacatures'
    | '/account/activate'
    | '/account/company'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/reset-password'
    | '/en/$'
    | '/vacatures/$slug'
    | '/account/'
    | '/en/'
    | '/account/company/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomSlugRoute: typeof CustomSlugRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CmsPreviewRoute: typeof CmsPreviewRoute
  CmsSyncRoute: typeof CmsSyncRoute
  ContactRoute: typeof ContactRoute
  OfferteRoute: typeof OfferteRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SchoonmaakbedrijfEnschedeRoute: typeof SchoonmaakbedrijfEnschedeRoute
  SchoonmaakbedrijfHengeloRoute: typeof SchoonmaakbedrijfHengeloRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VacaturesRoute: typeof VacaturesRouteWithChildren
  EnSplatRoute: typeof EnSplatRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$customSlug': {
      id: '/$customSlug'
      path: '/$customSlug'
      fullPath: '/$customSlug'
      preLoaderRoute: typeof CustomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms-preview': {
      id: '/cms-preview'
      path: '/cms-preview'
      fullPath: '/cms-preview'
      preLoaderRoute: typeof CmsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms-sync': {
      id: '/cms-sync'
      path: '/cms-sync'
      fullPath: '/cms-sync'
      preLoaderRoute: typeof CmsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schoonmaakbedrijf-enschede': {
      id: '/schoonmaakbedrijf-enschede'
      path: '/schoonmaakbedrijf-enschede'
      fullPath: '/schoonmaakbedrijf-enschede'
      preLoaderRoute: typeof SchoonmaakbedrijfEnschedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schoonmaakbedrijf-hengelo': {
      id: '/schoonmaakbedrijf-hengelo'
      path: '/schoonmaakbedrijf-hengelo'
      fullPath: '/schoonmaakbedrijf-hengelo'
      preLoaderRoute: typeof SchoonmaakbedrijfHengeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures': {
      id: '/vacatures'
      path: '/vacatures'
      fullPath: '/vacatures'
      preLoaderRoute: typeof VacaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/activate': {
      id: '/account/activate'
      path: '/activate'
      fullPath: '/account/activate'
      preLoaderRoute: typeof AccountActivateRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/company': {
      id: '/account/company'
      path: '/company'
      fullPath: '/account/company'
      preLoaderRoute: typeof AccountCompanyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/$': {
      id: '/en/$'
      path: '/en/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures/$slug': {
      id: '/vacatures/$slug'
      path: '/$slug'
      fullPath: '/vacatures/$slug'
      preLoaderRoute: typeof VacaturesSlugRouteImport
      parentRoute: typeof VacaturesRoute
    }
    '/account/company/users': {
      id: '/account/company/users'
      path: '/users'
      fullPath: '/account/company/users'
      preLoaderRoute: typeof AccountCompanyUsersRouteImport
      parentRoute: typeof AccountCompanyRoute
    }
  }
}

interface AccountCompanyRouteChildren {
  AccountCompanyUsersRoute: typeof AccountCompanyUsersRoute
}

const AccountCompanyRouteChildren: AccountCompanyRouteChildren = {
  AccountCompanyUsersRoute: AccountCompanyUsersRoute,
}

const AccountCompanyRouteWithChildren = AccountCompanyRoute._addFileChildren(
  AccountCompanyRouteChildren,
)

interface AccountRouteChildren {
  AccountActivateRoute: typeof AccountActivateRoute
  AccountCompanyRoute: typeof AccountCompanyRouteWithChildren
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountActivateRoute: AccountActivateRoute,
  AccountCompanyRoute: AccountCompanyRouteWithChildren,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface VacaturesRouteChildren {
  VacaturesSlugRoute: typeof VacaturesSlugRoute
}

const VacaturesRouteChildren: VacaturesRouteChildren = {
  VacaturesSlugRoute: VacaturesSlugRoute,
}

const VacaturesRouteWithChildren = VacaturesRoute._addFileChildren(
  VacaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomSlugRoute: CustomSlugRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CmsPreviewRoute: CmsPreviewRoute,
  CmsSyncRoute: CmsSyncRoute,
  ContactRoute: ContactRoute,
  OfferteRoute: OfferteRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SchoonmaakbedrijfEnschedeRoute: SchoonmaakbedrijfEnschedeRoute,
  SchoonmaakbedrijfHengeloRoute: SchoonmaakbedrijfHengeloRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VacaturesRoute: VacaturesRouteWithChildren,
  EnSplatRoute: EnSplatRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
