/**
 * Server-only entry for `@mccoy/database/server`.
 * Never import this from browser / client modules.
 */

export type {
  CreateWebsiteRequestInput,
  ListWebsiteRequestsFilter,
  WebsiteRequestsStore,
} from "./types";

export { attachmentMetaFromBase64, jsonWebsiteRequestsStore } from "./json-store";

export {
  createWebsiteRequest,
  updateRequestNotification,
  listWebsiteRequests,
  getWebsiteRequest,
  setWebsiteRequestStatus,
  setWebsiteRequestInquiryStatus,
  appendWebsiteRequestReply,
  updateWebsiteRequestSubmitterEmail,
  countWebsiteRequests,
  countWebsiteRequestsCreatedBetween,
  clearOrphanWebsiteRequestScopes,
  getWebsiteRequestsStore,
  supabaseWebsiteRequestsStore,
  loadActivePublishedFormScopeKeys,
  reconcileOrphanWebsiteRequestScopes,
  upsertWebsiteRequestMailMessage,
  listWebsiteRequestMailMessages,
  listKnownMailIdentitiesForMailbox,
  updateWebsiteRequestMailMessageAttachments,
  recordUnmatchedInboundMail,
  resolveUnmatchedInboundMail,
  listUnmatchedInboundMail,
  countOpenUnmatchedInboundMail,
  assertUnmatchedMailStaffAccess,
  listHiddenWebsiteRequestNumbers,
  findWebsiteRequestIdByGraphMessageId,
  findWebsiteRequestIdByNumber,
  type UnmatchedInboundMailInput,
  type RecordUnmatchedInboundMailResult,
  type UnmatchedInboundMailItem,
  type UnmatchedInboundMailCandidate,
  type UnmatchedInboundMailPage,
  type UnmatchedInboundMailReason,
  type UnmatchedInboundMailStatusFilter,
  type ListUnmatchedInboundMailQuery,
  type UnmatchedMailActorKind,
  type WebsiteRequestRow,
  type WebsiteRequestReplyRow,
  type WebsiteRequestMailMessageInput,
  type WebsiteRequestMailMessageRow,
  type WebsiteRequestMailAttachmentMeta,
  type UpsertMailMessageResult,
  type ReconcileOrphanScopesResult,
} from "./website-requests";
export {
  WEBSITE_REQUEST_ATTACHMENTS_BUCKET,
  WEBSITE_REQUEST_ATTACHMENT_MAX_BYTES,
  WEBSITE_REQUEST_ATTACHMENT_URL_TTL_SECONDS,
  websiteRequestAttachmentStoragePath,
  isWebsiteRequestUploadStoragePath,
  websiteRequestUploadStorageFilename,
  createWebsiteRequestAttachmentUploadSlots,
  assertWebsiteFormSubmissionQuota,
  storeWebsiteRequestAttachments,
  finalizeWebsiteRequestUploadedAttachments,
  getStoredWebsiteRequestAttachment,
  createStoredWebsiteRequestAttachmentAccess,
  cleanupExpiredWebsiteFormUploadBatches,
  isWebsiteRequestAttachmentPathOwnedByRequest,
  WebsiteFormAbuseLimitError,
  type WebsiteRequestAttachmentContent,
  type WebsiteRequestAttachmentUploadSlot,
  type StoreWebsiteRequestAttachmentsResult,
  type WebsiteRequestAttachmentAccess,
} from "./website-requests";
export {
  createSupabasePublishableClient,
  createSupabaseServiceClient,
  getSupabasePublicConfig,
  hasSupabasePublicConfig,
  hasSupabaseServiceConfig,
  SupabaseConfigError,
  type MccoySupabaseClient,
  type SupabasePublicConfig,
} from "./supabase";

export {
  getStaffUserById,
  getStaffUserByEmail,
  listStaffUsers,
  listActiveStaffUsers,
  countSuperAdmins,
  countActiveSuperAdmins,
  countRosterSuperAdmins,
  insertStaffProfile,
  ensureStaffProfileForInvite,
  findAuthUserIdByEmail,
  activateStaffUser,
  blockStaffUser,
  reinstateBlockedStaffUser,
  prepareStaffAccessRecovery,
  changeStaffRole,
  unbanAuthUser,
  deleteAuthStaffUser,
  deleteAuthTotpFactors,
  deleteAuthTotpFactorsExcept,
  updateStaffFullName,
  writeStaffAudit,
  createStaffInvitation,
  getActiveStaffInvitationByEmail,
  getStaffInvitationForAuthUser,
  markStaffInvitationSent,
  markStaffInvitationFailed,
  revokeActiveStaffInvitationsForEmail,
  isStaffInvitationAcceptable,
  acceptStaffInvitation,
  expireStaffInvitationIfNeeded,
  isStaffMfaRecoveryInvitation,
  type StaffInvitationPurpose,
  type InsertStaffProfileInput,
  type CreateStaffInvitationInput,
  type StaffInvitationRow,
} from "./staff";

export {
  shouldAbortSuperAdminBootstrap,
  decideStaffInviteForExistingEmail,
  shouldHardDeleteStaffOnRemove,
  staffInviteAuthLinkErrorMessage,
  isStaffBlocked,
  assertActiveSuperAdminActor,
  assertStaffProfileAllowsAdminSession,
  assertCanChangeStaffRole,
  assertCanRecoverStaffAccount,
  MAX_SUPER_ADMINS,
  messageIfPrivateSchemaMissing,
  staffInvitationDbErrorMessage,
  type StaffInviteEmailDecision,
} from "./staff-policy";

export {
  requireAdminSession,
  readAdminSession,
  getStaffAccessToken,
  countVerifiedTotpFactorsForAccessToken,
  establishStaffSessionFromTokens,
  establishStaffSessionFromEmailAuthCallback,
  hydrateBrowserStaffAuthFromCookies,
  hydrateRealtimeAccessToken,
  startMfaBrowserFlow,
  ensureMfaBrowserSession,
  completeMfaBrowserFlow,
  buildRealtimeAccessHydration,
  reestablishStaffSessionAfterPasswordSet,
  establishStaffSessionWithPassword,
  establishLegacyAdminSession,
  completeStaffMfaOnboarding,
  signOutAdminSessions,
  isStaffSupabaseAuthEnabled,
  type AdminSessionOptions,
  type AdminSessionView,
  type StaffAuthNextStep,
  type EstablishStaffSessionResult,
  type StaffSessionBrowserHydration,
  type RealtimeAccessHydration,
  type MfaBrowserSessionHydration,
} from "./staff-auth";

export {
  getOwnStaffSettingsProfile,
  updateOwnStaffProfile,
  changeOwnStaffEmail,
  changeOwnStaffPassword,
  getStaffPasswordRecoveryContext,
  completeStaffPasswordRecovery,
  assertStaffPasswordRecoveryTotpInput,
  getStaffMfaRecoveryContext,
  completeStaffMfaRecovery,
  type StaffMfaRecoveryContext,
  getSuperAdminSettingsOverview,
  changeStaffMemberRole,
  removeStaffMemberFromRoster,
  finalizeStaffAuthenticatorReplace,
  type StaffSettingsProfile,
  type StaffAccountResult,
  type StaffAccountFailure,
  type StaffPasswordRecoveryContext,
  type SuperAdminSettingsOverview,
} from "./staff-account";

export {
  DEFAULT_CMS_SITE_ID,
  DEFAULT_CMS_SITE_SLUG,
  getCmsStore,
  getFileCmsStore,
  createFileCmsStore,
  createSupabaseCmsStore,
  isSupabaseConnectivityError,
  markSupabaseCmsUnreachable,
  resolvePublicCmsRequest,
  buildPublishedSitemapEntries,
  buildCmsHeadFromSnapshot,
  resolvePublishedCmsPage,
  assertSitemapIndexabilityConsistency,
  collectSitemapEmittedUrls,
  processCmsOutbox,
  registerCmsPublishHook,
  ensureIndexNowPublishHookRegistered,
  notifyIndexNowForPublishEvent,
  submitIndexNowUrls,
  validateIndexNowUrl,
  builtinCmsSeedPages,
  importAetherStagedFixes,
  type AetherImportRow,
  type AetherImportResult,
  loadCmsPageForWebsiteForm,
  loadPublishedCmsPagesForFormScopes,
  getCachedPublishedCmsBundle,
  invalidatePublishedCmsReadCache,
  loadPublishedPagesBatched,
  type PublishedCmsBundleSnapshot,
  CMS_SEED_NAVIGATION,
  CMS_SEED_FOOTER,
  CMS_SEED_SCHEMA_VERSION,
  CMS_MEDIA_BUCKET,
  CMS_MEDIA_MAX_SOURCE_BYTES,
  CMS_MEDIA_MAX_STORED_BYTES,
  buildCmsMediaStoragePath,
  inspectCmsImageBytes,
  sanitizeOriginalFilename,
  sha256Hex,
  cmsMediaAssetId,
  storageCmsImage,
  getCmsMediaAsset,
  findCmsMediaAssetBySourcePath,
  normalizeCmsMediaSourcePath,
  listCmsMediaAssets,
  authorizeCmsMediaUpload,
  finalizeCmsMediaUpload,
  uploadCmsMediaBytes,
  updateCmsMediaMetadata,
  archiveCmsMediaAsset,
  restoreCmsMediaAsset,
  deleteCmsMediaAsset,
  findCmsMediaReferencesInPayloads,
  deriveCmsMediaPublicUrl,
  type CmsStore,
  type CmsSiteRecord,
  type CmsPageRecord,
  type CmsRevisionRecord,
  type CmsLocaleStateRecord,
  type CmsRedirectRecord,
  type CmsOutboxRecord,
  type CmsPublishedLookup,
  type PublishPageInput,
  type PublishPageResult,
  type RollbackPageInput,
  type UpsertPageInput,
  type DeletePageInput,
  type DeletePageResult,
  type PublicCmsResolveResult,
  type CmsOutboxConsumerResult,
  type CmsCacheInvalidationHook,
  type CmsMediaProfile,
  type CmsMediaStatus,
  type CmsMediaAsset,
  type CmsMediaListCursor,
  type CmsMediaReference,
} from "./cms";

export {
  NotificationOutboxUnavailableError,
  isNotificationOutboxUnavailableMessage,
  enqueueNotificationOutbox,
  listUnprocessedNotificationOutbox,
  markNotificationOutboxProcessed,
  markNotificationOutboxFailed,
  processNotificationOutbox,
  listForUser as listNotificationsForUser,
  unreadCount as notificationUnreadCount,
  listUnreadEntityIdsForUser as listUnreadNotificationEntityIds,
  markRead as markNotificationRead,
  markAllRead as markAllNotificationsRead,
  markReadForEntity as markNotificationsReadForEntity,
  dismiss as dismissNotification,
  markOpened as markNotificationOpened,
  listNotificationPreferencesForUser,
  setNotificationPreference,
  type NotificationRow,
  type NotificationRecipientRow,
  type NotificationPreferenceRow,
  type NotificationOutboxRow,
  type NotificationOutboxPayload,
  type EnqueueNotificationOutboxInput,
  type EnqueueNotificationOutboxResult,
  type NotificationListItem,
  type ListNotificationsForUserFilter,
  type ProcessNotificationOutboxResult,
  type NotificationPreferenceChannel,
  type NotificationPreferenceView,
} from "./notifications";

export {
  createCompany,
  getCompanyById,
  updateCompany,
  addCompanyMember,
  listCompaniesForUser,
  getCustomerById,
  getUserByNormalizedEmail,
  insertCustomerProfile,
  updateCustomerProfile,
  setCustomerBlocked,
  ensureGuestPurchaser,
  getGuestById,
  createOrder,
  listOrdersForCustomer,
  listOrdersForGuest,
  listOrderItems,
  linkOrdersToCustomer,
  markGuestConverted,
  listRegisteredCustomers,
  listGuestPurchasers,
  getCustomerLifetimeOrderStats,
  convertGuestPurchaser,
  inviteRegisteredCustomer,
  seedCommerceFixtures,
  commerceFixturesAllowed,
  seedAdminCustomersDirectoryDemo,
  listAdminCustomersDirectory,
  exportAdminCustomersDirectoryCsv,
  ADMIN_CUSTOMERS_EXPORT_MAX_ROWS,
  type AdminCustomersDirectoryExport,
  getAdminCustomersDirectoryDetail,
  recordAdminCustomerImportRun,
  exportCustomersCsv,
  parseCustomerImportCsv,
  importCustomersPreview,
  commitCustomerImport,
  type CommerceOrder,
  type CommerceOrderItem,
  type CustomerProfile,
  type RegisteredCustomerListItem,
  type GuestCustomerListItem,
  type CustomerListQuery,
  type CreateOrderInput,
  type ConvertGuestResult,
  type AdminCustomersDirectoryPage,
  type AdminCustomersDirectoryTab,
  listAdminPortalUsersDirectory,
  computePortalUsersKpis,
  selectedPortalUser,
  buildRegistrationTimeline,
  assertPortalUsersStaffAccess,
  type AdminPortalUserDirectoryItem,
  type AdminPortalUsersKpis,
  type AdminPortalUsersDirectoryPage,
  type AdminPortalUsersTruncation,
  ADMIN_PORTAL_USERS_SCAN_LIMIT,
  type AdminPortalUserTimelineStep,
  getPortalUserDetail,
  parseUserDetailKey,
  portalUserDetailAccess,
  type PortalUserDetail,
  type PortalUserLifetimeActivity,
  type PortalUserDetailActor,
  favouriteAdminAccessDecision,
  assertFavouriteAdminAccess,
  isProductEligibleToFavourite,
  insertCatalogueProduct,
  searchActiveProducts,
  listCompanyFavouriteProducts,
  addCompanyFavouriteProduct,
  removeCompanyFavouriteProduct,
  listPortalFavouriteProducts,
  addPortalFavouriteProduct,
  removePortalFavouriteProduct,
  FavouriteProductsError,
  type FavouriteActorKind,
} from "./commerce";

export {
  resolveCustomerPortalStatus,
  requireCustomerSession,
  readCustomerSession,
  requireAccountAdmin,
  customerSignInWithPassword,
  customerSignOut,
  customerRequestPasswordReset,
  customerCompletePasswordReset,
  activateCustomerAccount,
  peekInvitationByRawToken,
  resolveCustomerMembership,
  staffInviteAccountAdmin,
  staffInviteAccountUser,
  accountAdminInviteUser,
  resendPortalInvitation,
  listPortalCompanies,
  listCompanyMemberships,
  listInvitationsForCompany,
  listPendingInvitationsForCompany,
  suspendCompanyMembership,
  reactivateCompanyMembership,
  staffSuspendCompanyMembership,
  staffReactivateCompanyMembership,
  transferAccountAdmin,
  syncExistingServiceClients,
  previewExistingCustomerImport,
  commitExistingCustomerImport,
  deletePortalServiceCompanies,
  processCommerceEmailOutbox,
  processExpiredCustomerInvitations,
  CustomerPortalError,
  type CustomerSessionView,
  type PortalCompanyListItem,
  type ExistingCustomerImportPreview,
  type ExistingCustomerColumnMap,
} from "./customer-portal";

export { QUAL_PASSWORD } from "./customer-portal/qualification/seed";
export {
  applyQualificationEnv,
  isQualificationDbReachable,
} from "./customer-portal/qualification/env";
export {
  seedCustomerPortalE2eFixtures,
  writeCustomerPortalE2eFixtureFile,
  readCustomerPortalE2eFixtureFileSync,
  seedAbcFacilityE2eScenario,
  seedAbcFacilityMirrorAndSync,
  CUSTOMER_PORTAL_E2E_FIXTURE_PATH,
  type CustomerPortalE2eFixture,
  type AbcFacilityE2eFixture,
} from "./customer-portal/qualification/e2e-seed";
