/**
 * Server-only entry for `@mccoy/database/server`.
 * Never import this from browser / client modules.
 */

export type {
  CreateWebsiteRequestInput,
  ListWebsiteRequestsFilter,
  WebsiteRequestsStore,
} from "./types";

export { attachmentMetaFromBase64, jsonWebsiteRequestsStore } from "./json-store";

export {
  createWebsiteRequest,
  updateRequestNotification,
  listWebsiteRequests,
  getWebsiteRequest,
  setWebsiteRequestStatus,
  appendWebsiteRequestReply,
  countWebsiteRequests,
  getWebsiteRequestsStore,
  supabaseWebsiteRequestsStore,
  type WebsiteRequestRow,
  type WebsiteRequestReplyRow,
} from "./website-requests";

export {
  createSupabasePublishableClient,
  createSupabaseServiceClient,
  getSupabasePublicConfig,
  hasSupabasePublicConfig,
  hasSupabaseServiceConfig,
  SupabaseConfigError,
  type MccoySupabaseClient,
  type SupabasePublicConfig,
} from "./supabase";

export {
  getStaffUserById,
  getStaffUserByEmail,
  listStaffUsers,
  listActiveStaffUsers,
  countSuperAdmins,
  countActiveSuperAdmins,
  insertStaffProfile,
  ensureStaffProfileForInvite,
  findAuthUserIdByEmail,
  activateStaffUser,
  blockStaffUser,
  reinstateBlockedStaffUser,
  unbanAuthUser,
  deleteAuthTotpFactors,
  updateStaffFullName,
  writeStaffAudit,
  createStaffInvitation,
  getActiveStaffInvitationByEmail,
  getStaffInvitationForAuthUser,
  markStaffInvitationSent,
  markStaffInvitationFailed,
  revokeActiveStaffInvitationsForEmail,
  isStaffInvitationAcceptable,
  acceptStaffInvitation,
  expireStaffInvitationIfNeeded,
  type InsertStaffProfileInput,
  type CreateStaffInvitationInput,
  type StaffInvitationRow,
} from "./staff";

export {
  shouldAbortSuperAdminBootstrap,
  decideStaffInviteForExistingEmail,
  isStaffBlocked,
  assertActiveSuperAdminActor,
  assertStaffProfileAllowsAdminSession,
  messageIfPrivateSchemaMissing,
  type StaffInviteEmailDecision,
} from "./staff-policy";

export {
  requireAdminSession,
  readAdminSession,
  getStaffAccessToken,
  establishStaffSessionFromTokens,
  establishStaffSessionWithPassword,
  establishLegacyAdminSession,
  completeStaffMfaOnboarding,
  signOutAdminSessions,
  isStaffSupabaseAuthEnabled,
  type AdminSessionOptions,
  type AdminSessionView,
  type StaffAuthNextStep,
  type EstablishStaffSessionResult,
} from "./staff-auth";

export {
  getOwnStaffSettingsProfile,
  updateOwnStaffProfile,
  changeOwnStaffEmail,
  changeOwnStaffPassword,
  getSuperAdminSettingsOverview,
  removeStaffMemberFromRoster,
  type StaffSettingsProfile,
  type StaffAccountResult,
  type StaffAccountFailure,
  type SuperAdminSettingsOverview,
} from "./staff-account";

export {
  DEFAULT_CMS_SITE_ID,
  DEFAULT_CMS_SITE_SLUG,
  getCmsStore,
  getFileCmsStore,
  createFileCmsStore,
  createSupabaseCmsStore,
  isSupabaseConnectivityError,
  markSupabaseCmsUnreachable,
  resolvePublicCmsRequest,
  buildPublishedSitemapEntries,
  buildCmsHeadFromSnapshot,
  resolvePublishedCmsPage,
  processCmsOutbox,
  registerCmsPublishHook,
  builtinCmsSeedPages,
  CMS_SEED_NAVIGATION,
  CMS_SEED_SCHEMA_VERSION,
  CMS_MEDIA_BUCKET,
  CMS_MEDIA_MAX_SOURCE_BYTES,
  CMS_MEDIA_MAX_STORED_BYTES,
  buildCmsMediaStoragePath,
  inspectCmsImageBytes,
  sanitizeOriginalFilename,
  sha256Hex,
  cmsMediaAssetId,
  storageCmsImage,
  getCmsMediaAsset,
  findCmsMediaAssetBySourcePath,
  normalizeCmsMediaSourcePath,
  listCmsMediaAssets,
  authorizeCmsMediaUpload,
  finalizeCmsMediaUpload,
  uploadCmsMediaBytes,
  updateCmsMediaMetadata,
  archiveCmsMediaAsset,
  restoreCmsMediaAsset,
  deleteCmsMediaAsset,
  findCmsMediaReferencesInPayloads,
  deriveCmsMediaPublicUrl,
  type CmsStore,
  type CmsSiteRecord,
  type CmsPageRecord,
  type CmsRevisionRecord,
  type CmsLocaleStateRecord,
  type CmsRedirectRecord,
  type CmsOutboxRecord,
  type CmsPublishedLookup,
  type PublishPageInput,
  type PublishPageResult,
  type RollbackPageInput,
  type UpsertPageInput,
  type DeletePageInput,
  type DeletePageResult,
  type PublicCmsResolveResult,
  type CmsOutboxConsumerResult,
  type CmsCacheInvalidationHook,
  type CmsMediaProfile,
  type CmsMediaStatus,
  type CmsMediaAsset,
  type CmsMediaListCursor,
  type CmsMediaReference,
} from "./cms";

export {
  NotificationOutboxUnavailableError,
  isNotificationOutboxUnavailableMessage,
  enqueueNotificationOutbox,
  listUnprocessedNotificationOutbox,
  markNotificationOutboxProcessed,
  markNotificationOutboxFailed,
  processNotificationOutbox,
  listForUser as listNotificationsForUser,
  unreadCount as notificationUnreadCount,
  markRead as markNotificationRead,
  markAllRead as markAllNotificationsRead,
  dismiss as dismissNotification,
  markOpened as markNotificationOpened,
  listNotificationPreferencesForUser,
  setNotificationPreference,
  type NotificationRow,
  type NotificationRecipientRow,
  type NotificationPreferenceRow,
  type NotificationOutboxRow,
  type NotificationOutboxPayload,
  type EnqueueNotificationOutboxInput,
  type EnqueueNotificationOutboxResult,
  type NotificationListItem,
  type ListNotificationsForUserFilter,
  type ProcessNotificationOutboxResult,
  type NotificationPreferenceChannel,
  type NotificationPreferenceView,
} from "./notifications";
