/**
 * Server-only entry for `@mccoy/database/server`.
 * Never import this from browser / client modules.
 */

export type {
  CreateWebsiteRequestInput,
  ListWebsiteRequestsFilter,
  WebsiteRequestsStore,
} from "./types";

export { attachmentMetaFromBase64, jsonWebsiteRequestsStore } from "./json-store";

export {
  createWebsiteRequest,
  updateRequestNotification,
  listWebsiteRequests,
  getWebsiteRequest,
  setWebsiteRequestStatus,
  appendWebsiteRequestReply,
  countWebsiteRequests,
  countWebsiteRequestsCreatedBetween,
  clearOrphanWebsiteRequestScopes,
  getWebsiteRequestsStore,
  supabaseWebsiteRequestsStore,
  loadActivePublishedFormScopeKeys,
  reconcileOrphanWebsiteRequestScopes,
  upsertWebsiteRequestMailMessage,
  listWebsiteRequestMailMessages,
  listKnownMailIdentitiesForMailbox,
  listHiddenWebsiteRequestNumbers,
  findWebsiteRequestIdByGraphMessageId,
  findWebsiteRequestIdByNumber,
  type WebsiteRequestRow,
  type WebsiteRequestReplyRow,
  type WebsiteRequestMailMessageInput,
  type WebsiteRequestMailMessageRow,
  type UpsertMailMessageResult,
  type ReconcileOrphanScopesResult,
} from "./website-requests";
export {
  WEBSITE_REQUEST_ATTACHMENTS_BUCKET,
  WEBSITE_REQUEST_ATTACHMENT_MAX_BYTES,
  WEBSITE_REQUEST_ATTACHMENT_URL_TTL_SECONDS,
  websiteRequestAttachmentStoragePath,
  isWebsiteRequestUploadStoragePath,
  websiteRequestUploadStorageFilename,
  createWebsiteRequestAttachmentUploadSlots,
  storeWebsiteRequestAttachments,
  finalizeWebsiteRequestUploadedAttachments,
  getStoredWebsiteRequestAttachmentByPath,
  getStoredWebsiteRequestAttachment,
  createStoredWebsiteRequestAttachmentAccess,
  type WebsiteRequestAttachmentContent,
  type WebsiteRequestAttachmentUploadSlot,
  type StoreWebsiteRequestAttachmentsResult,
  type WebsiteRequestAttachmentAccess,
} from "./website-requests";
export {
  createSupabasePublishableClient,
  createSupabaseServiceClient,
  getSupabasePublicConfig,
  hasSupabasePublicConfig,
  hasSupabaseServiceConfig,
  SupabaseConfigError,
  type MccoySupabaseClient,
  type SupabasePublicConfig,
} from "./supabase";

export {
  getStaffUserById,
  getStaffUserByEmail,
  listStaffUsers,
  listActiveStaffUsers,
  countSuperAdmins,
  countActiveSuperAdmins,
  countRosterSuperAdmins,
  insertStaffProfile,
  ensureStaffProfileForInvite,
  findAuthUserIdByEmail,
  activateStaffUser,
  blockStaffUser,
  reinstateBlockedStaffUser,
  prepareStaffAccessRecovery,
  changeStaffRole,
  unbanAuthUser,
  deleteAuthStaffUser,
  deleteAuthTotpFactors,
  deleteAuthTotpFactorsExcept,
  updateStaffFullName,
  writeStaffAudit,
  createStaffInvitation,
  getActiveStaffInvitationByEmail,
  getStaffInvitationForAuthUser,
  markStaffInvitationSent,
  markStaffInvitationFailed,
  revokeActiveStaffInvitationsForEmail,
  isStaffInvitationAcceptable,
  acceptStaffInvitation,
  expireStaffInvitationIfNeeded,
  isStaffMfaRecoveryInvitation,
  type StaffInvitationPurpose,
  type InsertStaffProfileInput,
  type CreateStaffInvitationInput,
  type StaffInvitationRow,
} from "./staff";

export {
  shouldAbortSuperAdminBootstrap,
  decideStaffInviteForExistingEmail,
  shouldHardDeleteStaffOnRemove,
  staffInviteAuthLinkErrorMessage,
  isStaffBlocked,
  assertActiveSuperAdminActor,
  assertStaffProfileAllowsAdminSession,
  assertCanChangeStaffRole,
  assertCanRecoverStaffAccount,
  MAX_SUPER_ADMINS,
  messageIfPrivateSchemaMissing,
  staffInvitationDbErrorMessage,
  type StaffInviteEmailDecision,
} from "./staff-policy";

export {
  requireAdminSession,
  readAdminSession,
  getStaffAccessToken,
  countVerifiedTotpFactorsForAccessToken,
  establishStaffSessionFromTokens,
  establishStaffSessionFromEmailAuthCallback,
  hydrateBrowserStaffAuthFromCookies,
  hydrateRealtimeAccessToken,
  startMfaBrowserFlow,
  ensureMfaBrowserSession,
  completeMfaBrowserFlow,
  buildRealtimeAccessHydration,
  reestablishStaffSessionAfterPasswordSet,
  establishStaffSessionWithPassword,
  establishLegacyAdminSession,
  completeStaffMfaOnboarding,
  signOutAdminSessions,
  isStaffSupabaseAuthEnabled,
  type AdminSessionOptions,
  type AdminSessionView,
  type StaffAuthNextStep,
  type EstablishStaffSessionResult,
  type StaffSessionBrowserHydration,
  type RealtimeAccessHydration,
  type MfaBrowserSessionHydration,
} from "./staff-auth";

export {
  getOwnStaffSettingsProfile,
  updateOwnStaffProfile,
  changeOwnStaffEmail,
  changeOwnStaffPassword,
  getStaffPasswordRecoveryContext,
  completeStaffPasswordRecovery,
  assertStaffPasswordRecoveryTotpInput,
  getStaffMfaRecoveryContext,
  completeStaffMfaRecovery,
  type StaffMfaRecoveryContext,
  getSuperAdminSettingsOverview,
  changeStaffMemberRole,
  removeStaffMemberFromRoster,
  finalizeStaffAuthenticatorReplace,
  type StaffSettingsProfile,
  type StaffAccountResult,
  type StaffAccountFailure,
  type StaffPasswordRecoveryContext,
  type SuperAdminSettingsOverview,
} from "./staff-account";

export {
  DEFAULT_CMS_SITE_ID,
  DEFAULT_CMS_SITE_SLUG,
  getCmsStore,
  getFileCmsStore,
  createFileCmsStore,
  createSupabaseCmsStore,
  isSupabaseConnectivityError,
  markSupabaseCmsUnreachable,
  resolvePublicCmsRequest,
  buildPublishedSitemapEntries,
  buildCmsHeadFromSnapshot,
  resolvePublishedCmsPage,
  assertSitemapIndexabilityConsistency,
  collectSitemapEmittedUrls,
  processCmsOutbox,
  registerCmsPublishHook,
  ensureIndexNowPublishHookRegistered,
  notifyIndexNowForPublishEvent,
  submitIndexNowUrls,
  validateIndexNowUrl,
  builtinCmsSeedPages,
  loadCmsPageForWebsiteForm,
  loadPublishedCmsPagesForFormScopes,
  CMS_SEED_NAVIGATION,
  CMS_SEED_FOOTER,
  CMS_SEED_SCHEMA_VERSION,
  CMS_MEDIA_BUCKET,
  CMS_MEDIA_MAX_SOURCE_BYTES,
  CMS_MEDIA_MAX_STORED_BYTES,
  buildCmsMediaStoragePath,
  inspectCmsImageBytes,
  sanitizeOriginalFilename,
  sha256Hex,
  cmsMediaAssetId,
  storageCmsImage,
  getCmsMediaAsset,
  findCmsMediaAssetBySourcePath,
  normalizeCmsMediaSourcePath,
  listCmsMediaAssets,
  authorizeCmsMediaUpload,
  finalizeCmsMediaUpload,
  uploadCmsMediaBytes,
  updateCmsMediaMetadata,
  archiveCmsMediaAsset,
  restoreCmsMediaAsset,
  deleteCmsMediaAsset,
  findCmsMediaReferencesInPayloads,
  deriveCmsMediaPublicUrl,
  type CmsStore,
  type CmsSiteRecord,
  type CmsPageRecord,
  type CmsRevisionRecord,
  type CmsLocaleStateRecord,
  type CmsRedirectRecord,
  type CmsOutboxRecord,
  type CmsPublishedLookup,
  type PublishPageInput,
  type PublishPageResult,
  type RollbackPageInput,
  type UpsertPageInput,
  type DeletePageInput,
  type DeletePageResult,
  type PublicCmsResolveResult,
  type CmsOutboxConsumerResult,
  type CmsCacheInvalidationHook,
  type CmsMediaProfile,
  type CmsMediaStatus,
  type CmsMediaAsset,
  type CmsMediaListCursor,
  type CmsMediaReference,
} from "./cms";

export {
  NotificationOutboxUnavailableError,
  isNotificationOutboxUnavailableMessage,
  enqueueNotificationOutbox,
  listUnprocessedNotificationOutbox,
  markNotificationOutboxProcessed,
  markNotificationOutboxFailed,
  processNotificationOutbox,
  listForUser as listNotificationsForUser,
  unreadCount as notificationUnreadCount,
  markRead as markNotificationRead,
  markAllRead as markAllNotificationsRead,
  markReadForEntity as markNotificationsReadForEntity,
  dismiss as dismissNotification,
  markOpened as markNotificationOpened,
  listNotificationPreferencesForUser,
  setNotificationPreference,
  type NotificationRow,
  type NotificationRecipientRow,
  type NotificationPreferenceRow,
  type NotificationOutboxRow,
  type NotificationOutboxPayload,
  type EnqueueNotificationOutboxInput,
  type EnqueueNotificationOutboxResult,
  type NotificationListItem,
  type ListNotificationsForUserFilter,
  type ProcessNotificationOutboxResult,
  type NotificationPreferenceChannel,
  type NotificationPreferenceView,
} from "./notifications";
