-- Admin directory correctness:
--   1. Order statistics grouped by (customer_user_id, company_id) so a directory row
--      that displays one company never shows spend earned under another company.
--   2. Stable identifiers for company profile notes, replacing array-index targeting.
--
-- Read-path work only. No order row is created, deleted, or re-attributed here:
-- historical orders keep the company_id they were placed under.

-- ---------------------------------------------------------------------------
-- Company-scoped order statistics (service_role only)
-- ---------------------------------------------------------------------------

-- Groups by (customer_user_id, company_id). Orders without a company (guest
-- conversions that were never attributed) surface as a null company_id bucket
-- instead of being folded into an arbitrary company's totals.
create or replace function private.admin_order_stats_for_user_companies(p_user_ids uuid[])
returns table (
  customer_user_id uuid,
  company_id uuid,
  order_count bigint,
  total_spend_minor bigint,
  last_order_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    o.customer_user_id,
    o.company_id,
    count(*)::bigint as order_count,
    coalesce(
      sum(o.total_minor) filter (
        where o.payment_status = 'paid' and o.order_status <> 'cancelled'
      ),
      0
    )::bigint as total_spend_minor,
    max(o.placed_at) as last_order_at
  from public.orders o
  where o.customer_user_id = any (p_user_ids)
  group by o.customer_user_id, o.company_id;
$$;

comment on function private.admin_order_stats_for_user_companies(uuid[]) is
  'Order statistics per (user, company). Use for any admin row that displays a single company. private.admin_order_stats_for_users aggregates the same user across every company and is lifetime-only.';

revoke all on function private.admin_order_stats_for_user_companies(uuid[]) from public;
grant execute on function private.admin_order_stats_for_user_companies(uuid[]) to service_role;

create index if not exists orders_customer_company_placed_idx
  on public.orders (customer_user_id, company_id, placed_at desc)
  where customer_user_id is not null;

-- ---------------------------------------------------------------------------
-- Stable company note identifiers
-- ---------------------------------------------------------------------------

-- Notes are stored in public.companies.notes as blocks of "[stamp|author]\nbody".
-- Array indices shift when a concurrent edit adds or removes a note, so two staff
-- members could update or delete each other's note. This stamps every existing
-- header with "|#<uuid>" so edits can target an identifier instead.
--
-- Idempotent: a header that already carries "|#" is left untouched, and only the
-- leading bracket group of a line is rewritten, so note bodies are never altered.
create or replace function private.stamp_company_note_ids(p_notes text)
returns text
language plpgsql
volatile
set search_path = ''
as $$
declare
  v_lines text[];
  v_line text;
  v_out text[] := array[]::text[];
  v_close int;
  v_header text;
  v_rest text;
begin
  if p_notes is null or btrim(p_notes) = '' then
    return p_notes;
  end if;

  v_lines := string_to_array(p_notes, E'\n');

  foreach v_line in array v_lines loop
    v_close := position(']' in v_line);
    if left(v_line, 1) = '[' and v_close > 2 then
      v_header := substring(v_line from 2 for v_close - 2);
      v_rest := substring(v_line from v_close + 1);
      if position('|#' in v_header) = 0 then
        v_header := v_header || '|#' || gen_random_uuid()::text;
      end if;
      v_out := v_out || ('[' || v_header || ']' || v_rest);
    else
      v_out := v_out || v_line;
    end if;
  end loop;

  return array_to_string(v_out, E'\n');
end;
$$;

comment on function private.stamp_company_note_ids(text) is
  'Idempotent backfill helper: adds |#<uuid> to company note headers that have no stable id. Never edits note bodies.';

revoke all on function private.stamp_company_note_ids(text) from public;
grant execute on function private.stamp_company_note_ids(text) to service_role;

-- The backfill is a storage-format change, not a business event, so it must not
-- move companies.updated_at (the admin UI falls back to that timestamp when a
-- note carries no parseable date of its own).
alter table public.companies disable trigger companies_set_updated_at;

update public.companies c
set notes = private.stamp_company_note_ids(c.notes)
where c.notes is not null
  and btrim(c.notes) <> ''
  -- Comparison only detects "would this change anything"; the uuids generated by
  -- this probe are discarded and the SET clause generates the persisted ones.
  and private.stamp_company_note_ids(c.notes) is distinct from c.notes;

alter table public.companies enable trigger companies_set_updated_at;
